storm.zookeeper.servers:
    - "172.31.21.76"
    - "172.31.21.239"
    - "172.31.21.207"
storm.zookeeper.port: 2181
nimbus.seeds: ["172.31.21.76"]
storm.local.dir: "tmp/storm-data"
supervisor.slots.ports:
    - 6700
    - 6701
    - 6702
    - 6703
